server:
  port: 8084

spring:
  application:
    name: etl-service
  datasource:
    url: jdbc:postgresql://localhost:5432/analyticsdb
    username: ecom
    password: ecom
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

app:
  kafka:
    topic:
      order-created: order.created
      inventory-rejected: inventory.rejected
      payment-processed: payment.processed
      payment-failed: payment.failed

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
